# Generated by Django 2.2.1 on 2019-06-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiweb', '0012_auto_20190423_1707'),
        ('fpiweb', '0014_auto_20190523_2043'),
    ]

    operations = [
    ]
